//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUREF.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public decimal ID { get; set; }
        public decimal SensorID { get; set; }
        public System.DateTime DateofFlight { get; set; }
        public string AircraftID { get; set; }
        public string CallSign { get; set; }
        public string Mode3ACode { get; set; }
        public string TrackID { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public int R2_5M_NR { get; set; }
        public int R2_5M_NT { get; set; }
        public int R7_5M_NC_V { get; set; }
        public int R14_5M_NC_I { get; set; }
        public decimal R2_5M { get; set; }
        public decimal R7_5M { get; set; }
        public decimal R14_5M { get; set; }
        public int R2_5R_NR { get; set; }
        public int R2_5R_NT { get; set; }
        public int R7_5R_NC_V { get; set; }
        public int R14_5R_NC_I { get; set; }
        public decimal R2_5R { get; set; }
        public decimal R7_5R { get; set; }
        public decimal R14_5R { get; set; }
        public int R2_3M_NR { get; set; }
        public int R2_3M_NT { get; set; }
        public int R7_3M_NC_V { get; set; }
        public int R14_3M_NC_I { get; set; }
        public decimal R2_3M { get; set; }
        public decimal R7_3M { get; set; }
        public decimal R14_3M { get; set; }
        public int R2_3R_NR { get; set; }
        public int R2_3R_NT { get; set; }
        public int R7_3R_NC_V { get; set; }
        public int R14_3R_NC_I { get; set; }
        public decimal R2_3R { get; set; }
        public decimal R7_3R { get; set; }
        public decimal R14_3R { get; set; }
        public decimal NUCP { get; set; }
        public int R3_5M_NG_LONGGAP_COUNT { get; set; }
        public int R3_5R_NG_LONGGAP_COUNT { get; set; }
        public int R3_3M_NG_LONGGAP_COUNT { get; set; }
        public int R3_3R_NG_LONGGAP_COUNT { get; set; }
        public decimal R8_MFL_AGE_AVG { get; set; }
        public decimal R9_MFL_AGE_MAX { get; set; }
        public int R11_STABLE_FLIGHT { get; set; }
        public int R11_CLIMB_DESCEND_FLIGHT { get; set; }
        public int R11_IDENTIFY_FLIGHT_COUNT { get; set; }
        public int R6_3R_CLOSE_N { get; set; }
        public int R6_5R_CLOSE_N { get; set; }
        public decimal R6_3R_CLOSE_ZIGMA_E_SQ { get; set; }
        public decimal R6_5R_CLOSE_ZIGMA_E_SQ { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ProcessRound { get; set; }
        public int HasPlotInCAV { get; set; }
        public Nullable<int> Indicator { get; set; }
        public string Diagnose { get; set; }
    }
}
