//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUREF.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorView
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public string Description { get; set; }
    }
}
